### ISSUE TITLE
boolean dosent come out right

### ISSUE THREAD

**Issue by trondk** [Bryxxit/puppetdb-exporter#2]
im using the os_patching module fore puppet, and it put in a os_patching.reboots.reboot_required
into puppetdb.
That is a mixed true false and "missing"
but i dont get the value ?

**Comment by negast** [comment]
I'll test and look into it

**Comment by trondk** [comment]
Thanks :-) 

Im trying to the the result up in grafana, to show witch systems needs a
reboot.... :-) 

/T 

Inegast skrev den 2020-06-08 13:00: 

> I'll test and look into it 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1]
https://github.com/Bryxxit/puppetdb-exporter/issues/2#issuecomment-640532606
[2]

**Comment by negast** [comment]
Ok I think I've identified the problem will fix tomorrow

**Comment by trondk** [comment]
Cool thanks

Den 8. juni 2020 14.07.04 CEST, negast <notifications@github.com> skrev:
>Ok I think I've identified the problem will fix tomorrow
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Bryxxit/puppetdb-exporter/issues/2#issuecomment-640562381

-- 
Dette er sendt fra min mobiltelefon. Undskyld at jeg fatter mig i korthed.

**Comment by negast** [comment]
Ok I added a new release It should be fixed there. Can you test an get back to me?

**Comment by trondk** [comment]
Sure i Will chech Tomorrow

Den 9. juni 2020 07.27.57 CEST, negast <notifications@github.com> skrev:
>Ok I added a new release It should be fixed there. Can you test an get
>back to me?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Bryxxit/puppetdb-exporter/issues/2#issuecomment-641037418

-- 
Dette er sendt fra min mobiltelefon. Undskyld at jeg fatter mig i korthed.

**Comment by trondk** [comment]
hmmm it still seems that it comes out wrong....
puppetdb_facts_node_quage{fact="os_patching.reboots.reboot_required",node="comp111.example.com",puppet_environment="production",value=""} 1
puppetdb_facts_node_quage{fact="os_patching.reboots.reboot_required",node="comp247.example.com",puppet_environment="production",value="unknown"} 1

**Comment by negast** [comment]
Ok weird I tried one more thing. can you redownload the the latest release again?
I'm getting
puppetdb_facts_node_quage{fact="os_patching",node="node1",puppet_environment="test",value="false"} 1
puppetdb_facts_node_quage{fact="os_patching",node="node2",puppet_environment="test",value="unknown"} 1

For now not all host have this module I'll test this too.

**Comment by trondk** [comment]
Sure will try again 

negast skrev den 2020-06-12 07:31: 

> Ok weird I tried one more thing. can you redownload the the latest release again?
> I'm getting
> puppetdb_facts_node_quage{fact="os_patching",node="node1",puppet_environment="test",value="false"} 1
> puppetdb_facts_node_quage{fact="os_patching",node="node2",puppet_environment="test",value="unknown"} 1 
> 
> For now not all host have this module I'll test this too. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1]
https://github.com/Bryxxit/puppetdb-exporter/issues/2#issuecomment-643074056
[2]

**Comment by trondk** [comment]
nope i dosen't work 

ex 

{
 "certname": "example1.example.com",
 "environment": "production",
 "name": "os_patching",
 "value": {
 "pinned_packages": [],
 "blackouts": {},
 "block_patching_on_warnings": "false",
 "missing_update_kbs": [],
 "security_package_updates": [],
 "package_update_count": 0,
 "package_updates": [],
 "warnings": {},
 "last_run": {},
 "blocked_reasons": [],
 "blocked": false,
 "reboots": {
 "reboot_required": true
 },
 "reboot_override": "default",
 "security_package_update_count": 0,
 "patch_window": ""
 }
} 

the fact is not included in the export, the fact reboot_required for
example1.example.com is missing, its not there at all ? 

not even blank ?, is it because the exporter cant handle boolean ? 

/T 

negast skrev den 2020-06-12 07:31: 

> Ok weird I tried one more thing. can you redownload the the latest release again?
> I'm getting
> puppetdb_facts_node_quage{fact="os_patching",node="node1",puppet_environment="test",value="false"} 1
> puppetdb_facts_node_quage{fact="os_patching",node="node2",puppet_environment="test",value="unknown"} 1 
> 
> For now not all host have this module I'll test this too. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1]
https://github.com/Bryxxit/puppetdb-exporter/issues/2#issuecomment-643074056
[2]

**Comment by trondk** [comment]
I just curled the puppetdb, and the following different results out
      "reboot_required": "",
      "reboot_required": true
      "reboot_required": true
      "reboot_required": true
      "reboot_required": true
      "reboot_required": true
      "reboot_required": true
      "reboot_required": true
      "reboot_required": true,
      "reboot_required": "",
      "reboot_required": "",
      "reboot_required": "",
      "reboot_required": "",
      "reboot_required": "",
      "reboot_required": "unknown"
      "reboot_required": "",
      "reboot_required": "",
      "reboot_required": "",
      "reboot_required": "",
      "reboot_required": true
      "reboot_required": false,

If that is any help

**Comment by negast** [comment]
The first problem was indeed that I it couldn't handle boolean values I thought I fixed this but I'm testing now with the is_virtual fact and seems some things are not alright there. I'm looking into this as this might be the same problem that occurs. Do you perhaps also get any error messages or something from the exporter itself?

**Comment by negast** [comment]
Is_virtual now works for me but this won't fix your issue I think as it was just a human error of not adapting copied code fully.
I get something like the following:
puppetdb_facts_total{fact="is_virtual",value="false"} 9
puppetdb_facts_total{fact="is_virtual",value="true"} 89

I think i might have to create a costum fact and randomize it to hold similar data as you showed. This might take a bit longer and it will be for next week. The other thing I can also start doing is adding a more debug mode. So I might get more information as to what is going different in our environments.

**Comment by negast** [comment]
ok I wrote a simple fact
that randomey sets one of the following values "", "unknown", false or true.

When I poll it I get the correct values in total
# TYPE puppetdb_facts_total gauge
puppetdb_facts_total{fact="flurbo.reboots.reboots_required",value=""} 1
puppetdb_facts_total{fact="flurbo.reboots.reboots_required",value="false"} 3
puppetdb_facts_total{fact="flurbo.reboots.reboots_required",value="true"} 5
puppetdb_facts_total{fact="flurbo.reboots.reboots_required",value="unknown"} 1
but indeed it seems the per node fact labelled metrics are not showing up. This is probably the issue I'm gonna look into what is happening here

**Comment by trondk** [comment]
hmmm i think that i see the problem... 

puppetdb_facts_total{fact="flurbo.reboots.reboots_required",value="false"}
3 

the "false" is a string, not a boolean. 

i dumped some json 

"reboot_required": "unknown" <- "unknown" is a string, 

"reboot_required": false, <- false is a boolean 

so they mixes string and boolean in the os_patching module :-( 

which is bad style, ..... 

/T 

negast skrev den 2020-06-15 07:05: 

> ok I wrote a simple fact
> that randomey sets one of the following values "", "unknown", false or true. 
> 
> When I poll it I get the correct values in total 
> 
> TYPE PUPPETDB_FACTS_TOTAL GAUGE
> 
> puppetdb_facts_total{fact="flurbo.reboots.reboots_required",value=""} 1
> puppetdb_facts_total{fact="flurbo.reboots.reboots_required",value="false"} 3
> puppetdb_facts_total{fact="flurbo.reboots.reboots_required",value="true"} 5
> puppetdb_facts_total{fact="flurbo.reboots.reboots_required",value="unknown"} 1
> but indeed it seems the per node fact labelled metrics are not showing up. This is probably the issue I'm gonna look into what is happening here 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1]
https://github.com/Bryxxit/puppetdb-exporter/issues/2#issuecomment-643904377
[2]

**Comment by negast** [comment]
Ok I found the issue apparantly when copying I somehow copied the wrong array to add to. So the bool/string value was trying to add to an in based array. But this wouldn't work. I now added it to the correct array. And the values show up as they should. 

Booleans will act as strings for now. Indeed because the module has mixed bool and string I must do it this way. Else I could've have done something were bool values have there own gauge were false would be set to 0 and true to 1.

But you can get the latest releas again and test

**Comment by negast** [comment]
Well I could still do it the 0/1 way but I would have to set all the other values to false as well.

**Comment by trondk** [comment]
hmmm here is a curl from puppetdb. 

{
 "certname": "Example1.example.com",
 "environment": "production",
 "name": "os_patching",
 "value": {
 "pinned_packages": [],
 "blackouts": {},
 "block_patching_on_warnings": "false",
 "missing_update_kbs": [
 "KB890830",
 "KB4552926",
 "KB4562561",
 "KB4561616"
 ],
 "security_package_updates": [
 "2020-05 Cumulative Update for .NET Framework 4.8 for Windows Server
2016 for x64 (KB4552926)",
 "2020-06 Servicing Stack Update for Windows Server 2016 for x64-based
Systems (KB4562561)",
 "2020-06 Cumulative Update for Windows Server 2016 for x64-based
Systems (KB4561616)"
 ],
 "package_update_count": 4,
 "package_updates": [
 "Windows Malicious Software Removal Tool x64 - v5.82 (KB890830)",
 "2020-05 Cumulative Update for .NET Framework 4.8 for Windows Server
2016 for x64 (KB4552926)",
 "2020-06 Servicing Stack Update for Windows Server 2016 for x64-based
Systems (KB4562561)",
 "2020-06 Cumulative Update for Windows Server 2016 for x64-based
Systems (KB4561616)"
 ],
 "warnings": {},
 "last_run": {},
 "blocked_reasons": [],
 "blocked": false,
 "reboots": {
 "reboot_required": true
 },
 "reboot_override": "default",
 "security_package_update_count": 3,
 "patch_window": ""
 }
} 

this is the facts you get out about the reboot 

puppetdb_facts_node_quage{fact="os_patching.reboot_override",node="Example1.example.com",puppet_environment="production",value="default"}
1

it dosent seems the it get down into the 

"reboots": {
"reboot_required": true
}, 

negast skrev den 2020-06-15 07:33: 

> Ok I found the issue apparantly when copying I somehow copied the wrong array to add to. So the bool/string value was trying to add to an in based array. But this wouldn't work. I now added it to the correct array. And the values show up as they should. 
> 
> Booleans will act as strings for now. Indeed because the module has mixed bool and string I must do it this way. Else I could've have done something were bool values have there own gauge were false would be set to 0 and true to 1. 
> 
> But you can get the latest releas again and test 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1]
https://github.com/Bryxxit/puppetdb-exporter/issues/2#issuecomment-643912065
[2]

**Comment by negast** [comment]
How is your puppetdb-facts.yaml setup if you use a wildcard it might not go down all the way?

I always tested it like this
`
facts:
  - 'uptime_seconds'
  - 'is_virtual'
  - 'os_patching.reboots.reboots_required'
nodes: true
port: 8080
`

**Comment by negast** [comment]
Ok just to be sure I tested the latest version with a wild card.
This is the value of the custom fact I have
`
puppet facts
...
"flurbo": {
      "reboots": {
        "reboots_required": true
      },
      "values2": {
        "key1": "val1",
        "key2": "val2",
        "key3": 7,
        "key4": false
      },
      "key1": "val1",
      "key2": "val2",
      "key3": 7,
      "key4": false
    },
..
`

My puppetdb-facts.yaml
sorry commenting messes up yaml syntax
facts:
  - 'flurbo.*'

And I'm indeed missing a few hosts. These are probably the boolean hosts. I know this for certain as key4 is not present. So I'll also need to fix the boolean stuff for wildcard options.

If this is high priority I'd suggest doing as I mentioned previously and define the complete fact.
os_patching.reboots.reboots_required in your puppetdb-facts.yaml.

In the meantime I'll try and get this fixed for wildcard definitions.

**Comment by negast** [comment]
Ok it was an easy fix. Now when I do a wildcard value4 and the other boolean values show up.
puppetdb_facts_node_quage{fact="flurbo.key4",node="node1",puppet_environment="test",value="false"} 1
puppetdb_facts_node_quage{fact="flurbo.reboots.reboots_required",node="node1",puppet_environment="test",value=""} 1
puppetdb_facts_node_quage{fact="flurbo.reboots.reboots_required",node="node2",puppet_environment="test",value="false"} 1

So can you download the latest release again and try again?

**Comment by trondk** [comment]
Cool now it works :-) 

thanks 

/Tom 

negast skrev den 2020-06-15 13:03: 

> Ok it was an easy fix. Now when I do a wildcard value4 and the other boolean values show up.
> puppetdb_facts_node_quage{fact="flurbo.key4",node="node1",puppet_environment="test",value="false"} 1
> puppetdb_facts_node_quage{fact="flurbo.reboots.reboots_required",node="node1",puppet_environment="test",value=""} 1
> puppetdb_facts_node_quage{fact="flurbo.reboots.reboots_required",node="node2",puppet_environment="test",value="false"} 1 
> 
> So can you download the latest release again and try again? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1]
https://github.com/Bryxxit/puppetdb-exporter/issues/2#issuecomment-644060226
[2]

**Comment by negast** [comment]
cool. I'll close the issue then.
